#9 - Enable site isolation by default when deploying
ryangjchandler/forge-previewer pull request #10
Opened 2022-06-27 10:53 UTC by Illizian

2022-06-27 10:54 UTC, Illizian commented
Just need to check if we need to supplement this within the destroy command, as probably need to delete the user too :thinking:

2022-06-27 11:42 UTC, ryangjchandler commented
Can we flip the logic round so that it's an opt-in instead of an opt-out?

2022-07-03 11:44 UTC, Illizian commented
> Can we flip the logic round so that it's an opt-in instead of an opt-out?

This has been updated to, under the new flag `--site-isolation` :+1:

2022-07-13 15:08 UTC, ryangjchandler requested changes

2022-07-13 15:08 UTC, ryangjchandler commented on app/Commands/DeployCommand.php
> +        {--site-isolation : Enable site isolation.}
```suggestion
        {--isolate : Enable site isolation.}
```

2022-07-13 15:08 UTC, ryangjchandler commented on app/Commands/DeployCommand.php
> +        if ($this->option('site-isolation')) {
```suggestion
        if ($this->option('isolate')) {
```

2022-07-13 15:09 UTC, merged