Adds a flag to prevent database (& dotenv presumptions)
ryangjchandler/forge-previewer pull request #12
Opened 2022-06-27 12:01 UTC by Illizian

Closes #11

2022-06-27 12:44 UTC, Illizian commented
I just wanted to check on the destroy command to ensure this behaviour doesn't need replicating to both commands and would cause dependencies, but it iterates across existing databases within the destroy command so we should be good.

2022-07-13 15:11 UTC, ryangjchandler requested changes

2022-07-13 15:11 UTC, ryangjchandler commented on app/Commands/DeployCommand.php
> +        {--no-isolation : Avoid site isolation.}
This flag shouldn't be here.
```suggestion
```

2022-07-13 15:11 UTC, ryangjchandler requested changes

2022-07-13 15:11 UTC, ryangjchandler commented on app/Commands/DeployCommand.php
> +        {--no-database : Avoid creating a database.}';
```suggestion
        {--no-db : Avoid creating a database.}';
```

2022-07-13 15:11 UTC, ryangjchandler commented on app/Commands/DeployCommand.php
> +        if (!$this->option('no-database')) {
```suggestion
        if (! $this->option('no-db')) {
```

2022-07-13 15:11 UTC, ryangjchandler approved these changes

2022-07-13 15:12 UTC, merged